### PR TITLE
	No need for QuickTime to Start

### PR DESCRIPTION
**Pull request by suatfk**
```
modified:   xrecord.xcodeproj/project.pbxproj
new file:   xrecord/PluginHeader.h
new file:   xrecord/PluginHeaderHelper.cpp
new file:   xrecord/PluginHeaderHelper.h
deleted:    xrecord/QuickTime.h
modified:   xrecord/capture.swift
modified:   xrecord/main.swift
modified:   xrecord/support.h
deleted:    xrecord/support.m
new file:   xrecord/support.mm
```

### CODE REVIEW

**Comment by suatfk** [comment]
No need for QuickTime to start. Implemented iOSscreenCapturePlugin header so we after starting plugin directly and ios devices available in device list.  But need for wait plugin to start  and i give 5 sec to start .any suggestion accepted ? . Thanks.

**Comment by pmeenan** [comment]
Very cool.  I never felt good about the QuickTime hack.  I will do some testing on it to make sure it works on all the machines I have access to before merging.  I'm glad you removed the locking code because I was getting ready to do that too since the video capture was still flaky with multiple devices in that case.

Do you know if there is any way to deterministically tell if the plugin has started (ps or otherwise)?  I really hate fixed wait delays because it will be flaky and on fast systems will waste time but on slow disk systems may fail.

**Comment by suatfk** [comment]
Okey , CFPlugInIsLoadOnDemand() is controlling plugin for us but actually the biggest delay comes from startStream() method in plugin and its open Photos :D. I dont know why. 

I added a little code waiting for plugin load.

**Comment by pmeenan** [comment]
Worked beautifully, thanks.

**Pull request merged**
